[project]
name = "test-fastapi"
version = "0.1.0"
description = "A test project to learn FastAPI quickly"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.117.1",
]
